FROM sagebrew/django.web.primary.frontend:v5

MAINTAINER Devon Bleibtrey <devon@sagebrew.com>

RUN git clone -b <BRANCH> git@github.com:Sagebrew/com.sagebrew.frontend.git /home/apps/com.sagebrew.frontend/
RUN chown -R <APP_USER>:<APP_USER> /home/apps/
WORKDIR /home/apps/com.sagebrew.frontend/

RUN npm install
RUN bower install --config.interactive=false --allow-root
RUN ember build --environment <BRANCH>

CMD [ "ember", "deploy", "--environment", "<BRANCH>" ]